image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build job:
  stage: build
  variables:
    DOCKERHUB_REGISTRY: "https://index.docker.io/v1/"
    DOCKER_REGISTRY_DOCKERHUB_REPO: "anacha/openssh-client"
  only:
    - master
  script:
  - TMPTAG="7.5_p1-r8"
  - >-
    docker build --pull
    -t $CI_REGISTRY_IMAGE:latest
    -t $CI_REGISTRY_IMAGE:$TMPTAG
    .
  - docker push $CI_REGISTRY_IMAGE:$TMPTAG
  - docker push $CI_REGISTRY_IMAGE:latest
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:$TMPTAG
  - docker push $DOCKER_REGISTRY_DOCKERHUB_REPO:latest

  .job_sshpushtemplate: &sshpush
  before_script:
    - which ssh-agent || (apk add --no-cache --update openssh-client)
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - $([[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config) 
    # - ssh-keyscan -H 'bitbucket.org' >> ~/.ssh/known_hosts

Github Mirror:
  <<: *sshpush
  stage: git-push-to-mirror
  variables:
    GITHUB_REPO: "github.com:anacpe9/openssh-client.git"
  only:
    - master
  script:
    - echo "$GITHUB_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
    - git push --mirror git@$GITHUB_REPO
    - git push git@$GITHUB_REPO HEAD:master

Bitbucket Mirror:
  <<: *sshpush
  stage: git-push-to-mirror
  variables:
    BITBUCKET_REPO: "bitbucket.org:anacpe9/openssh-client.git"
  only:
    - master
  script:
    - echo "$BITBUCKET_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
    - git push --mirror git@$BITBUCKET_REPO
    - git push git@$BITBUCKET_REPO HEAD:master
